openapi: 3.0.0
info:
  contact:
    email: dev@approveapi.com
  description: The simple API to request a user's approval on anything via email + sms.
  title: ApproveAPISwagger
  version: 1.0.0
servers:
- url: https://approve.sh
paths:
  /prompt/{id}:
    get:
      description: Retrieve the prompt object with the given ID.
      operationId: GetPrompt
      parameters:
      - description: The identifier for a pending or completed prompt. This is returned when you create a prompt.
        explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      - description: If true, the request waits (long-polls) until the user responds to the prompt or more than 10 minutes pass. Defaults to false.
        explode: true
        in: query
        name: long_poll
        required: false
        schema:
          type: boolean
        style: form
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Prompt'
          description: OK
        404:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: A prompt with this identifier could not be found
      security:
      - apiKey: []
      summary: Retrieve a prompt
      tags:
      - approve
  /prompt/{id}/status:
    get:
      description: Returns whether a prompt has been completed by the user. This request does not require authentication, and so can be used client-side without sharing API credentials.
      operationId: GetPromptStatus
      parameters:
      - description: The prompt identifier.
        explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PromptStatus'
          description: OK
        404:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: A prompt with this identifier could not be found
      summary: Check prompt status
      tags:
      - approve
  /prompt:
    post:
      description: Creates a prompt and pushes it to the user (sends via email, sms, or other supported protocols).
      operationId: CreatePrompt
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreatePromptRequest'
        required: true
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Prompt'
          description: OK
        504:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Polling timed out with no user response
        401:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Missing or invalid API key in the username basic auth field
        400:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Invalid parameters
      security:
      - apiKey: []
      summary: Sending a prompt
      tags:
      - approve
components:
  responses:
    PromptNotFound:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
      description: A prompt with this identifier could not be found
    PollTimeout:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
      description: Polling timed out with no user response
    Unauthorized:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
      description: Missing or invalid API key in the username basic auth field
    BadRequest:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
      description: Invalid parameters
  schemas:
    PromptStatus:
      example:
        is_answered: true
      properties:
        is_answered:
          description: Whether the prompt has been answered or not.
          type: boolean
      required:
      - is_answered
      type: object
    CreatePromptRequest:
      example:
        metadata:
          browser: browser
          operating_system: operating_system
          location: location
          time: time
          ip_address: ip_address
        long_poll: true
        reject_text: reject_text
        approve_text: approve_text
        body: body
        title: title
        expires_in: 0.80082819046101150206595775671303272247314453125
        user: user
      properties:
        body:
          description: The body of the approval request to show the user.
          type: string
        title:
          description: The title of an approval request. Defaults to an empty string.
          type: string
        reject_text:
          description: The reject action text. Defaults to 'Reject'.
          type: string
        expires_in:
          description: The number of seconds until this request can no longer be answered.
          type: number
        long_poll:
          description: If true, the request waits (long-polls) until the user responds to the prompt or more than 10 minutes pass. Defaults to false.
          type: boolean
        user:
          description: The user to send the approval request to. Can be either an email address or a phone number.
          type: string
        approve_text:
          description: The approve action text. Defaults to 'Approve'.
          type: string
        metadata:
          $ref: '#/components/schemas/PromptMetadata'
      required:
      - body
      - user
      type: object
    Error:
      properties:
        error:
          description: A human readable API error message.
          type: string
      required:
      - error
      type: object
    Prompt:
      example:
        sent_at: 6.02745618307040320615897144307382404804229736328125
        metadata:
          browser: browser
          operating_system: operating_system
          location: location
          time: time
          ip_address: ip_address
        expires_at: 1.46581298050294517310021547018550336360931396484375
        answer:
          result: true
          metadata:
            browser: browser
            operating_system: operating_system
            ip_address: ip_address
          time: 0.80082819046101150206595775671303272247314453125
        id: id
      properties:
        answer:
          $ref: '#/components/schemas/PromptAnswer'
        sent_at:
          description: The unix timestamp when this prompt was sent.
          type: number
        id:
          description: A unique id for this prompt.
          type: string
        expires_at:
          description: The unix timestamp when this prompt can no longer be answered.
          type: number
        metadata:
          $ref: '#/components/schemas/PromptMetadata'
      required:
      - id
      - sent_at
      type: object
    AnswerMetadata:
      example:
        browser: browser
        operating_system: operating_system
        ip_address: ip_address
      properties:
        operating_system:
          type: string
        ip_address:
          type: string
        browser:
          type: string
      type: object
    PromptAnswer:
      example:
        result: true
        metadata:
          browser: browser
          operating_system: operating_system
          ip_address: ip_address
        time: 0.80082819046101150206595775671303272247314453125
      properties:
        time:
          description: The unix timestamp when the user answered the prompt.
          type: number
        result:
          description: The user's answer to whether or not they approve this prompt.
          type: boolean
        metadata:
          $ref: '#/components/schemas/AnswerMetadata'
      required:
      - result
      - time
      type: object
    PromptMetadata:
      example:
        browser: browser
        operating_system: operating_system
        location: location
        time: time
        ip_address: ip_address
      properties:
        time:
          description: The date/time of the action.
          type: string
        operating_system:
          description: The operating system initiating the action, i.e. Mac OS X.
          type: string
        ip_address:
          description: The IP address of the computer initiating the action.
          type: string
        location:
          description: The physical location, like Oakland, CA, of the action.
          type: string
        browser:
          description: The web browser initiating the action, i.e. Chrome.
          type: string
      type: object
  securitySchemes:
    apiKey:
      scheme: basic
      type: http
